/***************************************************************************
  loadexifdataset.cpp
  Load EXIF Dataset
  -------------------
         begin                : 2008-09-19
         copyright            : ( C ) Peter J. Ersts 2008
         email                : ersts at amnh.org

 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *( at your option ) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
/*  $Id: plugin.cpp 9327 2008-09-14 11:18:44Z jef $ */

//
// QGIS Specific includes
//

#include <qgisinterface.h>
#include <qgisgui.h>

#include "loadexifdataset.h"
#include "loadexifdatasetgui.h"

//
// Qt4 Related Includes
//

#include <QAction>
#include <QToolBar>


static const char * const sIdent = "$Id: plugin.cpp 9327 2008-09-14 11:18:44Z jef $";
static const QString sName = QObject::tr( "LoadEXIFDataset" );
static const QString sDescription = QObject::tr( "Load EXIF Dataset" );
static const QString sPluginVersion = QObject::tr( "Version 0.2" );
static const QgisPlugin::PLUGINTYPE sPluginType = QgisPlugin::UI;

//////////////////////////////////////////////////////////////////////
//
// THE FOLLOWING METHODS ARE MANDATORY FOR ALL PLUGINS
//
//////////////////////////////////////////////////////////////////////

/**
 * Constructor for the plugin. The plugin is passed a pointer
 * an interface object that provides access to exposed functions in QGIS.
 * @param theQGisInterface - Pointer to the QGIS interface object
 */
LoadExifDataset::LoadExifDataset( QgisInterface * theQgisInterface ):
    QgisPlugin( sName, sDescription, sPluginVersion, sPluginType ),
    mQGisIface( theQgisInterface )
{
}

LoadExifDataset::~LoadExifDataset( )
{

}

/*
 * Initialize the GUI interface for the plugin - this is only called once when the plugin is
 * added to the plugin registry in the QGIS application.
 */
void LoadExifDataset::initGui( )
{

  // Create the action for tool
  mQActionPointer = new QAction( QIcon( ":/loadexifdataset/icon.png" ), tr( "Load Exif Dataset" ), this );
  // Set the what's this text
  mQActionPointer->setWhatsThis( tr( "Create an vector point layer from a directory of geotagged images" ) );
  // Connect the action to the run
  connect( mQActionPointer, SIGNAL( triggered( ) ), this, SLOT( run( ) ) );
  // Add the icon to the toolbar
  mQGisIface->addToolBarIcon( mQActionPointer );
  mQGisIface->addPluginToMenu( tr( "&LoadExifDataset" ), mQActionPointer );

}
//method defined in interface
void LoadExifDataset::help( )
{
  //implement me!
}

// Slot called when the menu item is triggered
// If you created more menu items / toolbar buttons in initiGui, you should
// create a separate handler for each action - this single run( ) method will
// not be enough
void LoadExifDataset::run( )
{
  LoadExifDatasetGui *myPluginGui = new LoadExifDatasetGui( mQGisIface->mainWindow( ), QgisGui::ModalDialogFlags );
  myPluginGui->setAttribute( Qt::WA_DeleteOnClose );
  connect( myPluginGui, SIGNAL( draw( QString, QString ) ), this, SLOT( draw( QString, QString ) ) );
  myPluginGui->show( );
}

// Unload the plugin by cleaning up the GUI
void LoadExifDataset::unload( )
{
  // remove the GUI
  mQGisIface->removePluginMenu( "&LoadExifDataset", mQActionPointer );
  mQGisIface->removeToolBarIcon( mQActionPointer );
  delete mQActionPointer;
}

// Slot to pass along the draw layer call
void LoadExifDataset::draw( QString theDir, QString theLayerName )
{
  mQGisIface->addVectorLayer( theDir, theLayerName, "exif" );
}

//////////////////////////////////////////////////////////////////////////
//
//
//  THE FOLLOWING CODE IS AUTOGENERATED BY THE PLUGIN BUILDER SCRIPT
//    YOU WOULD NORMALLY NOT NEED TO MODIFY THIS, AND YOUR PLUGIN
//      MAY NOT WORK PROPERLY IF YOU MODIFY THIS INCORRECTLY
//
//
//////////////////////////////////////////////////////////////////////////


/**
 * Required extern functions needed  for every plugin
 * These functions can be called prior to creating an instance
 * of the plugin class
 */
// Class factory to return a new instance of the plugin class
QGISEXTERN QgisPlugin * classFactory( QgisInterface * theQgisInterfacePointer )
{
  return new LoadExifDataset( theQgisInterfacePointer );
}
// Return the name of the plugin - note that we do not user class members as
// the class may not yet be insantiated when this method is called.
QGISEXTERN QString name( )
{
  return sName;
}

// Return the description
QGISEXTERN QString description( )
{
  return sDescription;
}

// Return the type ( either UI or MapLayer plugin )
QGISEXTERN int type( )
{
  return sPluginType;
}

// Return the version number for the plugin
QGISEXTERN QString version( )
{
  return sPluginVersion;
}

// Delete ourself
QGISEXTERN void unload( QgisPlugin * thePluginPointer )
{
  delete thePluginPointer;
}
