%Module PyEasyGT 0

%Import QtCore/QtCoremod.sip
%Import QtGui/QtGuimod.sip

%Include egtapplication.sip
%Include egtapplicationinterface.sip
%Include egtdataprovider.sip
%Include egtexifeditor.sip
%Include egtexifengine.sip
%Include egtexiftaggroup.sip
%Include egtgpsexifengine.sip
%Include egtimagefactory.sip
%Include egtpathbuilder.sip
%Include egtplugininterface.sip
%Include egtphotoexifengine.sip
%Include egtrawimagereader.sip
